# -*- coding: utf-8 -*-
"""gamze süel - Gorev3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CMeMtryTkYl-TRRLQv_ZBN9aOpBE0b4

**1- 3x2 lik 1 lerden oluşan bir matris oluşturun**
"""

import numpy as np

np.ones((3,2), dtype=int)

"""**2- 2x5 6'lardan oluşan bir matris oluşturun**"""

import numpy as np
np.ones((2,5), dtype=int)*6

"""**3- 2-100 arası 2 şer atlayan bir array oluşturun**"""

np.arange (0,100,2)

"""**4- 3-10 arasında eşit dağılımlı 50 değer oluşturan bir array oluşturun**"""

np.linspace(3,10,50)

"""**5- 10 boyutunda sıfırlardan oluşan bir vektör (array) oluşturun, 5. değeri 1 olsun**"""

import numpy as np
a=np.zeros(10, dtype=int)
a[4]=1
a

"""**6- 0 dan 8 e kadar sıralı değerler barındıran 3x3 lük bir matris oluşturun**"""

np.arange(0,9).reshape(3,3)

"""**7- Rasgele sayılardan oluşan 3x3x3 lük bir array oluşturun**"""

np.random.random((3,3,3))

"""**8- 10x10 luk bir array oluşturun. Max ve min değerlerini bir değişkene atayın**"""

a=np.random.random((10,10))
a

a.min()

a.max()

"""**9- Birlerden oluşan 5x3 matrisi birlerden oluşan 3x2 matrisle çarpın**"""

a=np.ones((5,3), dtype=int)
b=np.ones((3,2), dtype=int)
a.dot(b)

"""**10- Her bir satırı 0 1 2 3 4 arrayinden oluşan 5x5 matris oluşturun**"""

import numpy as np

matris = np.array([0, 1, 2, 3, 4] * 5).reshape(5, 5)

print(matris)

"""**11- 10 elemanlı rastgele bir array oluşturun ve küçükten büyüğe sıralayın**"""

import numpy as np
a=np.random.random(10)
a

a = np.sort(a)
print(a)